services:
  freeradius:
    image: ghcr.io/nicksmith-vp/freeradius-mariadb:3.2.7-alpine
    networks:
        - docker_network
    logging:
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - /docker/conf/radius/conf/clients.conf:/etc/raddb/clients.conf
      - /docker/conf/radius/conf/radiusd.conf:/etc/raddb/radiusd.conf
      - /docker/conf/radius/conf/mods-enabled/sql:/etc/raddb/mods-enabled/sql
      - /docker/conf/radius/conf/sites-enabled/default:/etc/raddb/sites-enabled/default
      - /docker/conf/radius/dictionary/dictionary.audiocodes:/opt/share/freeradius/dictionary.audiocodes
      - /docker/conf/radius/dictionary/dictionary:/opt/share/freeradius/dictionary
    ports:
    - mode: ingress
      target: 1812
      published: 1812
      protocol: udp
    - mode: ingress
      target: 1813
      published: 1813
      protocol: udp
    command: "-X"

networks:
  docker_network: